pullSecret: "aliyun-acr-pull-secret"
gateway:
  image: crpi-wxtmmpsv7mbxgdvs.cn-hangzhou.personal.cr.aliyuncs.com/agenthub-dev/gateway
  tag: "v0.1.0-dev.d98e159"
  pullPolicy: Always
  port: 8080

ingressRoute:
  entryPoint: web

sandboxTemplates:
  sandbox:
    image: registry.k8s.io/e2e-test-images/echoserver:2.5
  agent:
    image: registry.k8s.io/e2e-test-images/echoserver:2.5

appConfig:
  log_level: INFO
  postgres:
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    username: postgres
    password: "269302"
    database: agenthub
  sandbox:
    namespace: sandbox
    port: 8080
    poll_interval: 1s
    selectors:
      - sandbox
      - agent
