apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenthub-gateway.fullname" . }}
  labels:
    {{- include "agenthub-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "agenthub-gateway.selectorLabels" . | nindent 4 }}
