apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenthub-gateway.fullname" . }}
  labels:
    {{- include "agenthub-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- omit .Values.appConfig "agentadaptor" | toYaml | nindent 4 }}
