apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "agenthub-gateway.fullname" . }}
  labels:
    {{- include "agenthub-gateway.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoint | default "web" | quote }}
  routes:
    - kind: Rule
      match: PathPrefix(`/socket.io`)
      priority: 30
      services:
        - kind: Service
          name: {{ include "agenthub-gateway.fullname" . }}
          port: {{ .Values.appConfig.gateway.port }}
    - kind: Rule
      match: PathPrefix(`/filesystem`)
      priority: 30
      services:
        - kind: Service
          name: {{ include "agenthub-gateway.fullname" . }}
          port: {{ .Values.appConfig.gateway.port }}
    - kind: Rule
      match: PathPrefix(`/api`)
      priority: 20
      services:
        - kind: Service
          name: {{ include "agenthub-gateway.fullstackBackendName" . }}
          port: {{ .Values.fullstack.backend.port }}
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 1
      services:
        - kind: Service
          name: {{ include "agenthub-gateway.fullstackFrontendName" . }}
          port: {{ .Values.fullstack.frontend.port }}
