apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenthub-gateway.fullname" . }}-agentadaptor
  namespace: {{ include "agenthub-gateway.sandboxNamespace" . }}
  labels:
    {{- include "agenthub-gateway.labels" . | nindent 4 }}
    agent: agent
data:
  config.json: |
    {{- toPrettyJson (.Values.appConfig.agentadaptor | default dict) | nindent 4 }}
