{{- $agentConfig := .Values.appConfig.agentadaptor | default dict -}}
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: {{ include "agenthub-gateway.fullname" . }}-agent
  namespace: {{ include "agenthub-gateway.sandboxNamespace" . }}
  labels:
    {{- include "agenthub-gateway.labels" . | nindent 4 }}
    agent: agent
spec:
  networkPolicyManagement: Unmanaged
  podTemplate:
    metadata:
      labels:
        agent: agent
    spec:
      dnsPolicy: ClusterFirst
      {{- if .Values.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret | quote }}
      {{- end }}
      containers:
        - name: agent
          image: {{ .Values.sandboxTemplates.agent.image | quote }}
          env:
            - name: AGENTADAPTOR_CONFIG_PATH
              value: /etc/agentadaptor/config.json
          ports:
            - name: http
              containerPort: {{ $agentConfig.port | default .Values.appConfig.sandbox.port }}
              protocol: TCP
          volumeMounts:
            - name: agentadaptor-config
              mountPath: /etc/agentadaptor/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: agentadaptor-config
          configMap:
            name: {{ include "agenthub-gateway.fullname" . }}-agentadaptor
